{"text": "2021-04-01 21:23:30.796 | INFO     | srso_signer.application:main:36 - Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)\n", "record": {"elapsed": {"repr": "0:00:00.178728", "seconds": 0.178728}, "exception": null, "extra": {"version": "0.1.15", "build_date": "2021-03-30T13:57:04.576032"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)", "module": "application", "name": "srso_signer.application", "process": {"id": 128730, "name": "MainProcess"}, "thread": {"id": 139867990013760, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:30.796390+03:00", "timestamp": 1617301410.79639}}}
{"text": "2021-04-01 21:23:37.439 | INFO     | srso_signer.application:main:36 - Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)\n", "record": {"elapsed": {"repr": "0:00:00.172847", "seconds": 0.172847}, "exception": null, "extra": {"version": "0.1.15", "build_date": "2021-03-30T13:57:04.576032"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)", "module": "application", "name": "srso_signer.application", "process": {"id": 128749, "name": "MainProcess"}, "thread": {"id": 140580722644800, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:37.439464+03:00", "timestamp": 1617301417.439464}}}
{"text": "2021-04-01 21:23:38.448 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.181385", "seconds": 1.181385}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 128749, "name": "MainProcess"}, "thread": {"id": 140580722644800, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:38.448002+03:00", "timestamp": 1617301418.448002}}}
{"text": "2021-04-01 21:23:38.449 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.183031", "seconds": 1.183031}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 128749, "name": "MainProcess"}, "thread": {"id": 140580722644800, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:38.449648+03:00", "timestamp": 1617301418.449648}}}
{"text": "2021-04-01 21:23:39.323 | ERROR    | srso_signer.console.commands.start:_handle_error:226 - Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:02.056846", "seconds": 2.056846}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 226, "message": "Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 128749, "name": "MainProcess"}, "thread": {"id": 140580722644800, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:39.323463+03:00", "timestamp": 1617301419.323463}}}
{"text": "2021-04-01 21:23:39.323 | ERROR    | srso_signer.console.commands.start:execute:116 - An error has been caught in function 'execute', process 'MainProcess' (128749), thread 'MainThread' (140580722644800):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 775, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 51, 'ErrorDesc': b'\\xd0\\xa1\\xd0\\xb5\\xd1\\x80\\xd1\\x82\\xd0\\xb8\\xd1\\x84\\xd1\\x96\\xd0\\xba\\xd0\\xb0\\xd1\\x82 \\xd0\\xbd\\xd0\\xb5 \\xd0\\xb7\\xd0\\xbd\\xd0\\xb0\\xd0\\xb9\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xbe'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 116, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 228, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 48, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 781, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:02.057211", "seconds": 2.057211}, "exception": {"type": "EUSignCPException", "value": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 116, "message": "An error has been caught in function 'execute', process 'MainProcess' (128749), thread 'MainThread' (140580722644800):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 128749, "name": "MainProcess"}, "thread": {"id": 140580722644800, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:23:39.323828+03:00", "timestamp": 1617301419.323828}}}
{"text": "2021-04-01 21:31:09.353 | INFO     | srso_signer.application:main:36 - Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)\n", "record": {"elapsed": {"repr": "0:00:00.174575", "seconds": 0.174575}, "exception": null, "extra": {"version": "0.1.15", "build_date": "2021-03-30T13:57:04.576032"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.15 (build date: 2021-03-30T13:57:04.576032)", "module": "application", "name": "srso_signer.application", "process": {"id": 130306, "name": "MainProcess"}, "thread": {"id": 140502835996480, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:31:09.353151+03:00", "timestamp": 1617301869.353151}}}
{"text": "2021-04-01 21:31:10.358 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.179967", "seconds": 1.179967}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 130306, "name": "MainProcess"}, "thread": {"id": 140502835996480, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:31:10.358543+03:00", "timestamp": 1617301870.358543}}}
{"text": "2021-04-01 21:31:10.359 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.180546", "seconds": 1.180546}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 130306, "name": "MainProcess"}, "thread": {"id": 140502835996480, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:31:10.359122+03:00", "timestamp": 1617301870.359122}}}
{"text": "2021-04-01 21:31:11.029 | ERROR    | srso_signer.console.commands.start:_handle_error:226 - Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:01.851017", "seconds": 1.851017}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 226, "message": "Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 130306, "name": "MainProcess"}, "thread": {"id": 140502835996480, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:31:11.029593+03:00", "timestamp": 1617301871.029593}}}
{"text": "2021-04-01 21:31:11.030 | ERROR    | srso_signer.console.commands.start:execute:116 - An error has been caught in function 'execute', process 'MainProcess' (130306), thread 'MainThread' (140502835996480):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 775, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 51, 'ErrorDesc': b'\\xd0\\xa1\\xd0\\xb5\\xd1\\x80\\xd1\\x82\\xd0\\xb8\\xd1\\x84\\xd1\\x96\\xd0\\xba\\xd0\\xb0\\xd1\\x82 \\xd0\\xbd\\xd0\\xb5 \\xd0\\xb7\\xd0\\xbd\\xd0\\xb0\\xd0\\xb9\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xbe'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 116, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 228, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 48, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 781, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:01.852174", "seconds": 1.852174}, "exception": {"type": "EUSignCPException", "value": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 116, "message": "An error has been caught in function 'execute', process 'MainProcess' (130306), thread 'MainThread' (140502835996480):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 130306, "name": "MainProcess"}, "thread": {"id": 140502835996480, "name": "MainThread"}, "time": {"repr": "2021-04-01 21:31:11.030750+03:00", "timestamp": 1617301871.03075}}}
