{"text": "2021-03-10 16:55:51.902 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:02.995871", "seconds": 2.995871}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 6660, "name": "MainProcess"}, "thread": {"id": 140473345279808, "name": "MainThread"}, "time": {"repr": "2021-03-10 16:55:51.902950+02:00", "timestamp": 1615388151.90295}}}
{"text": "2021-03-10 16:55:54.309 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: u87\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-test.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False\n", "record": {"elapsed": {"repr": "0:00:05.401984", "seconds": 5.401984}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: u87\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-test.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 6660, "name": "MainProcess"}, "thread": {"id": 140473345279808, "name": "MainThread"}, "time": {"repr": "2021-03-10 16:55:54.309063+02:00", "timestamp": 1615388154.309063}}}
{"text": "2021-03-10 16:55:54.310 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:05.403102", "seconds": 5.403102}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 6660, "name": "MainProcess"}, "thread": {"id": 140473345279808, "name": "MainThread"}, "time": {"repr": "2021-03-10 16:55:54.310181+02:00", "timestamp": 1615388154.310181}}}
{"text": "2021-03-10 16:55:55.536 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:06.629034", "seconds": 6.629034}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 6660, "name": "MainProcess"}, "thread": {"id": 140473345279808, "name": "MainThread"}, "time": {"repr": "2021-03-10 16:55:55.536113+02:00", "timestamp": 1615388155.536113}}}
{"text": "2021-03-10 16:55:55.537 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (6660), thread 'MainThread' (140473345279808):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 51, 'ErrorDesc': b'\\xd0\\xa1\\xd0\\xb5\\xd1\\x80\\xd1\\x82\\xd0\\xb8\\xd1\\x84\\xd1\\x96\\xd0\\xba\\xd0\\xb0\\xd1\\x82 \\xd0\\xbd\\xd0\\xb5 \\xd0\\xb7\\xd0\\xbd\\xd0\\xb0\\xd0\\xb9\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xbe'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)\n", "record": {"elapsed": {"repr": "0:00:06.630193", "seconds": 6.630193}, "exception": {"type": "EUSignCPException", "value": "\u0421\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e (51)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (6660), thread 'MainThread' (140473345279808):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 6660, "name": "MainProcess"}, "thread": {"id": 140473345279808, "name": "MainThread"}, "time": {"repr": "2021-03-10 16:55:55.537272+02:00", "timestamp": 1615388155.537272}}}
{"text": "2021-03-10 17:52:37.880 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.171241", "seconds": 0.171241}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 16983, "name": "MainProcess"}, "thread": {"id": 139891600934720, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:37.880149+02:00", "timestamp": 1615391557.880149}}}
{"text": "2021-03-10 17:52:38.860 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False\n", "record": {"elapsed": {"repr": "0:00:01.151163", "seconds": 1.151163}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 16983, "name": "MainProcess"}, "thread": {"id": 139891600934720, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:38.860071+02:00", "timestamp": 1615391558.860071}}}
{"text": "2021-03-10 17:52:38.860 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.151515", "seconds": 1.151515}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 16983, "name": "MainProcess"}, "thread": {"id": 139891600934720, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:38.860423+02:00", "timestamp": 1615391558.860423}}}
{"text": "2021-03-10 17:52:38.880 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.171355", "seconds": 1.171355}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 16983, "name": "MainProcess"}, "thread": {"id": 139891600934720, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:38.880263+02:00", "timestamp": 1615391558.880263}}}
{"text": "2021-03-10 17:52:38.880 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (16983), thread 'MainThread' (139891600934720):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.171674", "seconds": 1.171674}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (16983), thread 'MainThread' (139891600934720):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 16983, "name": "MainProcess"}, "thread": {"id": 139891600934720, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:38.880582+02:00", "timestamp": 1615391558.880582}}}
{"text": "2021-03-10 17:52:50.442 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.175840", "seconds": 0.17584}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17013, "name": "MainProcess"}, "thread": {"id": 140459483916096, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:52:50.442373+02:00", "timestamp": 1615391570.442373}}}
{"text": "2021-03-10 17:53:32.649 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.172147", "seconds": 0.172147}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17103, "name": "MainProcess"}, "thread": {"id": 140680872585024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:32.649861+02:00", "timestamp": 1615391612.649861}}}
{"text": "2021-03-10 17:53:33.651 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False\n", "record": {"elapsed": {"repr": "0:00:01.173811", "seconds": 1.173811}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17103, "name": "MainProcess"}, "thread": {"id": 140680872585024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:33.651525+02:00", "timestamp": 1615391613.651525}}}
{"text": "2021-03-10 17:53:33.652 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.174637", "seconds": 1.174637}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17103, "name": "MainProcess"}, "thread": {"id": 140680872585024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:33.652351+02:00", "timestamp": 1615391613.652351}}}
{"text": "2021-03-10 17:53:33.680 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.203181", "seconds": 1.203181}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17103, "name": "MainProcess"}, "thread": {"id": 140680872585024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:33.680895+02:00", "timestamp": 1615391613.680895}}}
{"text": "2021-03-10 17:53:33.681 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (17103), thread 'MainThread' (140680872585024):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.203508", "seconds": 1.203508}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (17103), thread 'MainThread' (140680872585024):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17103, "name": "MainProcess"}, "thread": {"id": 140680872585024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:33.681222+02:00", "timestamp": 1615391613.681222}}}
{"text": "2021-03-10 17:53:48.307 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.246253", "seconds": 0.246253}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17137, "name": "MainProcess"}, "thread": {"id": 140588439689024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:48.307896+02:00", "timestamp": 1615391628.307896}}}
{"text": "2021-03-10 17:53:49.356 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False\n", "record": {"elapsed": {"repr": "0:00:01.295133", "seconds": 1.295133}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-03-2021.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: False", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17137, "name": "MainProcess"}, "thread": {"id": 140588439689024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:49.356776+02:00", "timestamp": 1615391629.356776}}}
{"text": "2021-03-10 17:53:49.357 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.295624", "seconds": 1.295624}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17137, "name": "MainProcess"}, "thread": {"id": 140588439689024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:49.357267+02:00", "timestamp": 1615391629.357267}}}
{"text": "2021-03-10 17:53:49.390 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.328371", "seconds": 1.328371}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17137, "name": "MainProcess"}, "thread": {"id": 140588439689024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:49.390014+02:00", "timestamp": 1615391629.390014}}}
{"text": "2021-03-10 17:53:49.390 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (17137), thread 'MainThread' (140588439689024):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.328710", "seconds": 1.32871}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (17137), thread 'MainThread' (140588439689024):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17137, "name": "MainProcess"}, "thread": {"id": 140588439689024, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:53:49.390353+02:00", "timestamp": 1615391629.390353}}}
{"text": "2021-03-10 17:55:26.165 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.168468", "seconds": 0.168468}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17461, "name": "MainProcess"}, "thread": {"id": 140143889426240, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:55:26.165654+02:00", "timestamp": 1615391726.165654}}}
{"text": "2021-03-10 17:56:22.103 | INFO     | srso_signer.console.commands.configure:handle:26 - Setup configuration: {\n  \"names\": [\n    \"\u041a\u041d\u0415\u0414\u041f - \u0406\u0414\u0414 \u0414\u041f\u0421\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u0414\u0424\u0421\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u041c\u0456\u043d\u0434\u043e\u0445\u043e\u0434\u0456\u0432\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u0414\u041f\u0421\"\n  ],\n  \"address\": \"acskidd.gov.ua\",\n  \"force_offline\": false,\n  \"ocsp\": {\n    \"address\": \"acskidd.gov.ua/services/ocsp/\",\n    \"port\": 80\n  },\n  \"cmp\": {\n    \"address\": \"acskidd.gov.ua\"\n  },\n  \"tsp\": {\n    \"address\": \"acskidd.gov.ua\",\n    \"port\": 80\n  }\n}\n", "record": {"elapsed": {"repr": "0:00:56.106371", "seconds": 56.106371}, "exception": null, "extra": {}, "file": {"name": "configure.py", "path": "srso_signer/console/commands/configure.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 26, "message": "Setup configuration: {\n  \"names\": [\n    \"\u041a\u041d\u0415\u0414\u041f - \u0406\u0414\u0414 \u0414\u041f\u0421\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u0414\u0424\u0421\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u041c\u0456\u043d\u0434\u043e\u0445\u043e\u0434\u0456\u0432\",\n    \"\u0410\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d\u0438\u0439 \u0446\u0435\u043d\u0442\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0446\u0456\u0457 \u043a\u043b\u044e\u0447\u0456\u0432 \u0406\u0414\u0414 \u0414\u041f\u0421\"\n  ],\n  \"address\": \"acskidd.gov.ua\",\n  \"force_offline\": false,\n  \"ocsp\": {\n    \"address\": \"acskidd.gov.ua/services/ocsp/\",\n    \"port\": 80\n  },\n  \"cmp\": {\n    \"address\": \"acskidd.gov.ua\"\n  },\n  \"tsp\": {\n    \"address\": \"acskidd.gov.ua\",\n    \"port\": 80\n  }\n}", "module": "configure", "name": "srso_signer.console.commands.configure", "process": {"id": 17461, "name": "MainProcess"}, "thread": {"id": 140143889426240, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:56:22.103557+02:00", "timestamp": 1615391782.103557}}}
{"text": "2021-03-10 17:57:08.010 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.162750", "seconds": 0.16275}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17754, "name": "MainProcess"}, "thread": {"id": 140158032299840, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:08.010382+02:00", "timestamp": 1615391828.010382}}}
{"text": "2021-03-10 17:57:13.555 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.170749", "seconds": 0.170749}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 17771, "name": "MainProcess"}, "thread": {"id": 139908042270528, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:13.555263+02:00", "timestamp": 1615391833.555263}}}
{"text": "2021-03-10 17:57:14.540 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-0321.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.156287", "seconds": 1.156287}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6-0321.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17771, "name": "MainProcess"}, "thread": {"id": 139908042270528, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:14.540801+02:00", "timestamp": 1615391834.540801}}}
{"text": "2021-03-10 17:57:14.541 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.156608", "seconds": 1.156608}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17771, "name": "MainProcess"}, "thread": {"id": 139908042270528, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:14.541122+02:00", "timestamp": 1615391834.541122}}}
{"text": "2021-03-10 17:57:14.561 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.176580", "seconds": 1.17658}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17771, "name": "MainProcess"}, "thread": {"id": 139908042270528, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:14.561094+02:00", "timestamp": 1615391834.561094}}}
{"text": "2021-03-10 17:57:14.561 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (17771), thread 'MainThread' (139908042270528):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.176913", "seconds": 1.176913}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (17771), thread 'MainThread' (139908042270528):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 17771, "name": "MainProcess"}, "thread": {"id": 139908042270528, "name": "MainThread"}, "time": {"repr": "2021-03-10 17:57:14.561427+02:00", "timestamp": 1615391834.561427}}}
{"text": "2021-03-10 18:00:03.620 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.171034", "seconds": 0.171034}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 18328, "name": "MainProcess"}, "thread": {"id": 139778081421120, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:03.620805+02:00", "timestamp": 1615392003.620805}}}
{"text": "2021-03-10 18:00:04.604 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.154875", "seconds": 1.154875}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18328, "name": "MainProcess"}, "thread": {"id": 139778081421120, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:04.604646+02:00", "timestamp": 1615392004.604646}}}
{"text": "2021-03-10 18:00:04.605 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.155351", "seconds": 1.155351}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18328, "name": "MainProcess"}, "thread": {"id": 139778081421120, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:04.605122+02:00", "timestamp": 1615392004.605122}}}
{"text": "2021-03-10 18:00:04.632 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.182446", "seconds": 1.182446}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18328, "name": "MainProcess"}, "thread": {"id": 139778081421120, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:04.632217+02:00", "timestamp": 1615392004.632217}}}
{"text": "2021-03-10 18:00:04.632 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (18328), thread 'MainThread' (139778081421120):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.182780", "seconds": 1.18278}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (18328), thread 'MainThread' (139778081421120):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18328, "name": "MainProcess"}, "thread": {"id": 139778081421120, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:04.632551+02:00", "timestamp": 1615392004.632551}}}
{"text": "2021-03-10 18:00:21.288 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.173792", "seconds": 0.173792}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 18372, "name": "MainProcess"}, "thread": {"id": 139881865848640, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:21.288324+02:00", "timestamp": 1615392021.288324}}}
{"text": "2021-03-10 18:00:22.266 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test100322\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.151862", "seconds": 1.151862}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test100322\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18372, "name": "MainProcess"}, "thread": {"id": 139881865848640, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:22.266394+02:00", "timestamp": 1615392022.266394}}}
{"text": "2021-03-10 18:00:22.266 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.152208", "seconds": 1.152208}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18372, "name": "MainProcess"}, "thread": {"id": 139881865848640, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:22.266740+02:00", "timestamp": 1615392022.26674}}}
{"text": "2021-03-10 18:00:22.286 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.171780", "seconds": 1.17178}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18372, "name": "MainProcess"}, "thread": {"id": 139881865848640, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:22.286312+02:00", "timestamp": 1615392022.286312}}}
{"text": "2021-03-10 18:00:22.286 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (18372), thread 'MainThread' (139881865848640):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.172112", "seconds": 1.172112}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (18372), thread 'MainThread' (139881865848640):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18372, "name": "MainProcess"}, "thread": {"id": 139881865848640, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:22.286644+02:00", "timestamp": 1615392022.286644}}}
{"text": "2021-03-10 18:00:43.716 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.170329", "seconds": 0.170329}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 18443, "name": "MainProcess"}, "thread": {"id": 140135042656064, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:43.716238+02:00", "timestamp": 1615392043.716238}}}
{"text": "2021-03-10 18:00:44.694 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.148851", "seconds": 1.148851}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/modules/TooPro/tps_pay_method/prro/Key-6 (40) (1).dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18443, "name": "MainProcess"}, "thread": {"id": 140135042656064, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:44.694760+02:00", "timestamp": 1615392044.69476}}}
{"text": "2021-03-10 18:00:44.695 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.149234", "seconds": 1.149234}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18443, "name": "MainProcess"}, "thread": {"id": 140135042656064, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:44.695143+02:00", "timestamp": 1615392044.695143}}}
{"text": "2021-03-10 18:00:44.715 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.169652", "seconds": 1.169652}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18443, "name": "MainProcess"}, "thread": {"id": 140135042656064, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:44.715561+02:00", "timestamp": 1615392044.715561}}}
{"text": "2021-03-10 18:00:44.715 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (18443), thread 'MainThread' (140135042656064):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.169959", "seconds": 1.169959}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (18443), thread 'MainThread' (140135042656064):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 18443, "name": "MainProcess"}, "thread": {"id": 140135042656064, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:00:44.715868+02:00", "timestamp": 1615392044.715868}}}
{"text": "2021-03-10 18:05:11.274 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.166908", "seconds": 0.166908}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 19290, "name": "MainProcess"}, "thread": {"id": 139624360163136, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:05:11.274466+02:00", "timestamp": 1615392311.274466}}}
{"text": "2021-03-10 18:05:12.259 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6-0321.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.152390", "seconds": 1.15239}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6-0321.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19290, "name": "MainProcess"}, "thread": {"id": 139624360163136, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:05:12.259948+02:00", "timestamp": 1615392312.259948}}}
{"text": "2021-03-10 18:05:12.260 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.153187", "seconds": 1.153187}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19290, "name": "MainProcess"}, "thread": {"id": 139624360163136, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:05:12.260745+02:00", "timestamp": 1615392312.260745}}}
{"text": "2021-03-10 18:05:12.280 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.173130", "seconds": 1.17313}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19290, "name": "MainProcess"}, "thread": {"id": 139624360163136, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:05:12.280688+02:00", "timestamp": 1615392312.280688}}}
{"text": "2021-03-10 18:05:12.281 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (19290), thread 'MainThread' (139624360163136):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.173475", "seconds": 1.173475}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (19290), thread 'MainThread' (139624360163136):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19290, "name": "MainProcess"}, "thread": {"id": 139624360163136, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:05:12.281033+02:00", "timestamp": 1615392312.281033}}}
{"text": "2021-03-10 18:07:20.140 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.167291", "seconds": 0.167291}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 19748, "name": "MainProcess"}, "thread": {"id": 140282787379008, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:20.140686+02:00", "timestamp": 1615392440.140686}}}
{"text": "2021-03-10 18:07:21.149 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.176590", "seconds": 1.17659}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19748, "name": "MainProcess"}, "thread": {"id": 140282787379008, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:21.149985+02:00", "timestamp": 1615392441.149985}}}
{"text": "2021-03-10 18:07:21.150 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.177396", "seconds": 1.177396}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19748, "name": "MainProcess"}, "thread": {"id": 140282787379008, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:21.150791+02:00", "timestamp": 1615392441.150791}}}
{"text": "2021-03-10 18:07:21.178 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.205073", "seconds": 1.205073}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19748, "name": "MainProcess"}, "thread": {"id": 140282787379008, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:21.178468+02:00", "timestamp": 1615392441.178468}}}
{"text": "2021-03-10 18:07:21.178 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (19748), thread 'MainThread' (140282787379008):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.205383", "seconds": 1.205383}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (19748), thread 'MainThread' (140282787379008):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19748, "name": "MainProcess"}, "thread": {"id": 140282787379008, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:21.178778+02:00", "timestamp": 1615392441.178778}}}
{"text": "2021-03-10 18:07:43.532 | INFO     | srso_signer.application:main:36 - Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)\n", "record": {"elapsed": {"repr": "0:00:00.170970", "seconds": 0.17097}, "exception": null, "extra": {"version": "0.1.8", "build_date": "2021-02-15T08:33:12.681049"}, "file": {"name": "application.py", "path": "srso_signer/application.py"}, "function": "main", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 36, "message": "Start application v0.1.8 (build date: 2021-02-15T08:33:12.681049)", "module": "application", "name": "srso_signer.application", "process": {"id": 19835, "name": "MainProcess"}, "thread": {"id": 140716804941632, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:43.532862+02:00", "timestamp": 1615392463.532862}}}
{"text": "2021-03-10 18:07:44.512 | INFO     | srso_signer.console.commands.start:handle:72 - config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True\n", "record": {"elapsed": {"repr": "0:00:01.150399", "seconds": 1.150399}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "handle", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 72, "message": "config:\n login: test10032\n api_url: https://dev-api.checkbox.in.ua\n key: /var/www/petr.tps.my/sites/all/libraries/prro/Key-6.dat\n jks_index: 0\n ssl_verify: True\n infinity: True\n websocket: True", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19835, "name": "MainProcess"}, "thread": {"id": 140716804941632, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:44.512291+02:00", "timestamp": 1615392464.512291}}}
{"text": "2021-03-10 18:07:44.512 | INFO     | srso_signer.console.commands.start:execute:105 - Load key...\n", "record": {"elapsed": {"repr": "0:00:01.150749", "seconds": 1.150749}, "exception": null, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 105, "message": "Load key...", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19835, "name": "MainProcess"}, "thread": {"id": 140716804941632, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:44.512641+02:00", "timestamp": 1615392464.512641}}}
{"text": "2021-03-10 18:07:44.532 | ERROR    | srso_signer.console.commands.start:_handle_error:204 - Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.170393", "seconds": 1.170393}, "exception": null, "extra": {"name": "EUSignCPException", "e": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)"}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "_handle_error", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 204, "message": "Failed to process request - EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19835, "name": "MainProcess"}, "thread": {"id": 140716804941632, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:44.532285+02:00", "timestamp": 1615392464.532285}}}
{"text": "2021-03-10 18:07:44.532 | ERROR    | srso_signer.console.commands.start:execute:115 - An error has been caught in function 'execute', process 'MainProcess' (19835), thread 'MainThread' (140716804941632):\nTraceback (most recent call last):\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 759, in read_private_key_file\n\n  File \"src/srso_signer/vendor/EUSignCP/lib/linux_x86_64/EUSignCP.py\", line 2653, in ReadPrivateKeyFile\n\nRuntimeError: {'ErrorCode': 24, 'ErrorDesc': b'\\xd0\\x92\\xd0\\xb8\\xd0\\xbd\\xd0\\xb8\\xd0\\xba\\xd0\\xbb\\xd0\\xb0 \\xd0\\xbf\\xd0\\xbe\\xd0\\xbc\\xd0\\xb8\\xd0\\xbb\\xd0\\xba\\xd0\\xb0 \\xd0\\xbf\\xd1\\x80\\xd0\\xb8 \\xd0\\xb2\\xd1\\x96\\xd0\\xb4\\xd0\\xba\\xd1\\x80\\xd0\\xb8\\xd1\\x82\\xd1\\x82\\xd1\\x96 \\xd0\\xbe\\xd1\\x81\\xd0\\xbe\\xd0\\xb1\\xd0\\xb8\\xd1\\x81\\xd1\\x82\\xd0\\xbe\\xd0\\xb3\\xd0\\xbe \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87\\xd0\\xb0 (\\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd1\\x96\\xd1\\x80\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9 \\xd0\\xbf\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xbb\\xd1\\x8c \\xd1\\x87\\xd0\\xb8 \\xd0\\xba\\xd0\\xbb\\xd1\\x8e\\xd1\\x87 \\xd0\\xbf\\xd0\\xbe\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb4\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd0\\xb8\\xd0\\xb9)'}\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"srso_signer/main.py\", line 4, in <module>\n\n  File \"srso_signer/application.py\", line 43, in main\n\n  File \"clikit/console_application.py\", line 131, in run\n\n  File \"clikit/api/command/command.py\", line 120, in handle\n\n  File \"clikit/api/command/command.py\", line 171, in _do_handle\n\n  File \"cleo/commands/command.py\", line 92, in wrap_handle\n\n  File \"srso_signer/console/commands/start.py\", line 82, in handle\n\n> File \"srso_signer/console/commands/start.py\", line 115, in execute\n\n  File \"srso_signer/console/commands/start.py\", line 206, in _handle_error\n\n  File \"srso_signer/console/commands/start.py\", line 107, in execute\n\n  File \"srso_signer/signer/signer.py\", line 47, in load_key\n\n  File \"srso_signer/vendor/EUSignCP/extension/simple.py\", line 765, in read_private_key_file\n\nsrso_signer.vendor.EUSignCP.extension.exceptions.EUSignCPException: \u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)\n", "record": {"elapsed": {"repr": "0:00:01.170719", "seconds": 1.170719}, "exception": {"type": "EUSignCPException", "value": "\u0412\u0438\u043d\u0438\u043a\u043b\u0430 \u043f\u043e\u043c\u0438\u043b\u043a\u0430 \u043f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u043e\u0441\u043e\u0431\u0438\u0441\u0442\u043e\u0433\u043e \u043a\u043b\u044e\u0447\u0430 (\u043d\u0435\u0432\u0456\u0440\u043d\u0438\u0439 \u043f\u0430\u0440\u043e\u043b\u044c \u0447\u0438 \u043a\u043b\u044e\u0447 \u043f\u043e\u0448\u043a\u043e\u0434\u0436\u0435\u043d\u0438\u0439) (24)", "traceback": true}, "extra": {}, "file": {"name": "start.py", "path": "srso_signer/console/commands/start.py"}, "function": "execute", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 115, "message": "An error has been caught in function 'execute', process 'MainProcess' (19835), thread 'MainThread' (140716804941632):", "module": "start", "name": "srso_signer.console.commands.start", "process": {"id": 19835, "name": "MainProcess"}, "thread": {"id": 140716804941632, "name": "MainThread"}, "time": {"repr": "2021-03-10 18:07:44.532611+02:00", "timestamp": 1615392464.532611}}}
